### DISCUSSION TITLE
Feature demand: export PDF with watermark

### DISCUSSION THREAD

**Discussion by how2051** [l1xnan/obsidian-better-export-pdf#164] [General]
Hi, I wonder if it's planed to have feature that export PDF with watermark?

Sometimes I wanna export some of my notes to other, and I want to add some watermark such as the author name(my name), created time, etc.

I'd appreciated it if you want to impl this feature, or anyone who can do it.
If this feature is not planed to impl, I think I may try my best to do it myself, then could anyone give me some guidance or suggestion that how can I do to do so?

I've tried to use the `sample plugin` from Obsidian to do this, but I got stuck at exporting PDF :(
Is there a simplest way to export PDF ?  maybe there're some API from Obsidian that I can call ?
I asked for help on Discord, but got no reply

sorry if I bother you

**Comment by l1xnan** [comment]
You can achieve a watermark-like effect by adding HTML snippets in the document and supplementing them with custom CSS snippets.

`your-note.md`:
```markdown
<div class="watermark">Your Watermark Text</div>

## Title 1
main content
```

css snippets `watermark.css`:
```css
.watermark {
  display: none;
}

@media print {
  .watermark {
    page-break-after: always;
    display: block;
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 24px;
    color: rgba(0, 0, 0, 0.1);
    pointer-events: none;
    page-break-after: always;
  }
}
```
