### DISCUSSION TITLE
Page break for each note

### DISCUSSION THREAD

**Discussion by BerylTP** [l1xnan/obsidian-better-export-pdf#200] [General]
In export folder to PDF, is it possible to insert a page break for each note within the folder or subfolders?

**Comment by l1xnan** [comment]
Add CSS snippets:
```css
.markdown-preview-view > section {
  page-break-after: always;
}
```
The HTML structure is as follows:
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/ae3bed9f-e645-4cc1-99be-05603d838594)
