### DISCUSSION TITLE
怎么修改文件名标题的颜色。

### DISCUSSION THREAD

**Discussion by Zhufuning** [l1xnan/obsidian-better-export-pdf#239] [Q&A]
导出的文件名标题跟随H1的颜色，但是我想让它是黑色的。
![屏幕截图 2024-06-11 143118](https://github.com/l1xnan/obsidian-better-export-pdf/assets/156870073/77cb1d00-df5d-4b63-a872-53dca44e733b)
![屏幕截图 2024-06-11 143147](https://github.com/l1xnan/obsidian-better-export-pdf/assets/156870073/93a8d869-bf4d-4541-a304-9e11ddc3edff)

**Comment by l1xnan** [comment]
添加类似这样的自定义CSS片段：
```css
body {
  --h1-color: #000;
}
body h1:first-child {
  color: #000 !important;
}
```
