### ISSUE TITLE
Feature Request: Define page's separation in the preview

### ISSUE THREAD

**Issue by LBF38** [l1xnan/obsidian-better-export-pdf#107]
Hi @l1xnan,

Thanks for this cool plugin ! 

I would like to suggest a feature: be able to define page separations for the exported file. 
Currently, when I export any of my notes, some parts are cut-off at the end of a page, like a bullet list, or a note preview, ... 
It would be awesome to be able to set page breakpoints so that it is easier and prettier to export MD files to PDF.

Thanks in advance for taking it into account !

**Comment by l1xnan** [comment]
Do you want to set page breaks manually? You can try to solve it with custom `css snippets`:
```css
/* print.css */
.page-break {
  height: 1px;
  background-color: gray;
}

@media print {
  .page-break {
    background-color: white;
    page-break-before: always;
    clear: both;
  }
}
```
Then, in your document `node.md`, where you want the page breaks to be, add the
```markdown
<!-- node.md -->

Previous page content

<div class="page-break"></div>

Next page content
```
Not sure if this will meet your expectations?
