### ISSUE TITLE
Top margin doesn't work after page 2

### ISSUE THREAD

**Issue by wyliu721** [l1xnan/obsidian-better-export-pdf#125]
There is no space between the main text and the header.

**Comment by wyliu721** [comment]
Solved. The header will occupy the top of the page. Top margin must be more than 10mm (such as 15 or 20mm) to visually separate the main text and the header.

**Comment by ChrisG661** [comment]
I had the same issue, it was not the header template that is occupying the top margin of the first page. Rather, it was the padding set by the class `.markdown-preview-view` that you have to override by setting it to 0 to make sure that all pages have the same margin.

This is the CSS snippet I am using:
```css
@media print {
  .markdown-preview-view {
    padding: 0 !important; /* or padding-top */
  }
}
```
