### ISSUE TITLE
Use the same frontmatter tags that are used by pandoc to drive the conversion from markdown to pdf

### ISSUE THREAD

**Issue by gbonazzoli** [l1xnan/obsidian-better-export-pdf#157]
We use the following "pandoc" tags in the frontmatter in order to drive the conversion to pdf.

```yaml
title: {{title}}
subtitle: WIN Project AS-IS
author: [Author]
date: {{date:YYYY-MM-DD}}
page-background: "ColombiniGroupBackground.pdf"
titlepage-background: CopertinaColombinigroup.jpg
titlepage: true
titlepage-logo: "ColombiniGroupLogo.jpeg"
logo-width: 34mm
toc: false
toc-own-page: false
toc-title: Table of Contents
papersize: a4
geometry:
  - top=24mm
  - left=15mm
  - right=15mm
  - bottom=26mm
code-block-font-size: \tiny
lang: "it"
table-use-row-colors: "true"
```

if you use the same tags there will be no duplication and an exstablished same nomenclature.
