### ISSUE TITLE
如何设置PDF的字体以及字体的大小？

### ISSUE THREAD

**Issue by victorwwd** [l1xnan/obsidian-better-export-pdf#181]
如何设置PDF的字体以及字体的大小？

**Comment by l1xnan** [comment]
可以通过自定义 css 片段设置，例如：
```css
@media print {
  body {
    --font-interface-override: "霞鹜文楷" !important;
    --font-text-override: "霞鹜文楷" !important;
    --font-print-override: "霞鹜文楷" !important;
    --font-monospace-override: "霞鹜文楷等宽" !important;
    --font-text-size: 30px !important;
  }
```
如果你想仅针对某类元素设置，可以自定修改 css 选择器
