### ISSUE TITLE
How to print with a custom css file?

### ISSUE THREAD

**Issue by merlinuwe** [l1xnan/obsidian-better-export-pdf#224]
I guess, that using css for printing is buggy.

In my testvault i saw that I could chose one of some (not all) of the css files. But this pull down _dissapeared_. Now it looks so:

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4138869/432691bc-2e21-45a8-8ff5-33c56f15196b)

What can I do to print with a custom css file?

The css file is activated:

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4138869/c48ffab5-dea5-4236-a5ea-ca4fc909c78f)

When I press the debug button, I get this messages:

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4138869/34ff7f03-3023-4681-9b03-e6cd0eafb6d8)

SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 13
	Plugins enabled: 1
		1: Better Export PDF v1.8.0

**Comment by l1xnan** [comment]
First, relevant configurations need to be enabled. 
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/5d020483-ab5e-4ea5-b9ae-7b6d203490db)
Then, in the export pdf modal, only CSS snippet that are not enabled in the "Appearance > CSS Snippets" section can be selected.
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/f04261b4-5e06-43df-941d-c432d2bef6b6)

**Comment by merlinuwe** [comment]
Thank you very much, I must have overlooked the passage in the documentation, sorry. Now I can select the betterexportpdf.css.

But the css you provided first doesn't change anything in the pdf file.

```css
@media print {
  body {
    font-size: 20px !important;
    font-family: "Times New Roman" !important;
  }
}
```

But this one works:

```css
@media print {
  body {
    --font-interface-override: "Times New Roman" !important;
    --font-text-override: "Times New Roman" !important;
    --font-print-override: "Times New Roman" !important;
    --font-monospace-override: "Consolas" !important;
    --font-text-size: 20px !important;
    font-family: "Times New Roman" !important;
    color: red !important;
  }
}
```

But not with this css (color):

```
@media print {
  body {
    --font-interface-override: "Times New Roman" !important;
    --font-text-override: "Times New Roman" !important;
    --font-print-override: "Times New Roman" !important;
    --font-monospace-override: "Consolas" !important;
    --font-text-size: 20px !important;
    font-family: "Times New Roman" !important;
    color: red !important;
    background: lime !important;
  }
}
```

The color is ignored (or set false by me?)
The background is lime in the preview but not in the output pdf file.

What css can I use for manipulating and testing the print?

**Comment by l1xnan** [comment]
Additionally, there may indeed be inconsistencies between the preview and the actual results. CSS defined within `@media print {}` will not take effect by default. I will extract the CSS from `@media print {}` to apply it to the current preview page, aiming to achieve the desired print preview effect. However, due to CSS specificity, discrepancies may still exist between the preview and the actual outcome.

**Comment by merlinuwe** [comment]
Thank you very much. 

An example printing css file would be helpful, so that the user can adjust the settings instead of building them from scratch.

**Comment by l1xnan** [comment]
> Thank you very much.
> 
> An example printing css file would be helpful, so that the user can adjust the settings instead of building them from scratch.

Thank you for your suggestion. Customizing CSS requires a certain level of expertise, which can be challenging for most Obsidian users. We need more examples to lower this barrier to entry.

**Comment by merlinuwe** [comment]
This is a first attempt by me and my friend chatGPT. ;-)

It doesn't look bad with my long and complex documents, but it needs improvement.

Maybe this or a further development of it will help the users.


```css
@media print {
    /* Allgemeine Schriftart und -größe */
     body {
         --mu-table-th-background: black !important;  /* Das sind  erstaunlicherweise die senkrechte Linien durch eine Tabelle */
         --font-interface-override: "Times New Roman" !important;
         --font-text-override: "Times New Roman" !important;
         --font-print-override: "Times New Roman" !important;
         --font-monospace-override: "Consolas" !important;
         --font-text-size: 12pt !important;
         font-family: "Times New Roman" !important;
         font-size: 12pt !important;
         margin: 0;
         padding: 0;
    }
    /* Abstand zur Kopf- und Fußzeile */
     @page {
         margin-top: 15mm;
        /* Vergrößert den oberen Abstand auf ca. 1,5 cm */
         margin-bottom: 20mm;
    }
    /* Abstand zwischen Kopfzeile und erstem Element */
     body::before {
         content: '';
         display: block;
         height: 15mm;
        /* Vergrößert den Abstand zur oberen Seite */
    }
    /* Überschriftenebenen 1-6 in fett und #0e2841 (das dunkle Blau aus Word) */
     h1, h2, h3, h4, h5, h6 {
         font-weight: bold;
         color: #0e2841;
         background: none !important;
         page-break-after: avoid;
        /* Vermeidet Seitenumbrüche nach Überschriften */
    }
    /* Bild- und Tabellenüberschriften (caption) in #0e2841 */
     caption, figcaption {
         font-weight: bold;
         color: #0e2841;
         text-align: center;
        /* Zentriert Bild- und Tabellenüberschriften */
    }
    /* Bilder zentrieren, verkleinern und auf die nächste Seite verschieben, wenn nötig */
     img {
         display: block;
         margin-left: auto;
         margin-right: auto;
         max-width: 100%;
        /* Verkleinert das Bild, wenn es zu groß ist */
         height: auto;
         max-height: 100vh;
        /* Verkleinert das Bild, wenn es zu hoch ist */
         page-break-before: avoid;
        /* Ermöglicht Seitenumbruch vor dem Bild, falls nötig */
         page-break-inside: avoid;
        /* Vermeidet Seitenumbrüche innerhalb von Bildern */
         page-break-after: avoid;
        /* Vermeidet Seitenumbrüche nach Bildern;
         Uwe */
    }
    /* Tabellen zentrieren */
     table {
         display: block;
         margin-left: auto;
         margin-right: auto;
         page-break-inside: avoid;
        /* Vermeidet Seitenumbrüche innerhalb von Tabellen */
         margin-top: 0;
        /* Kein Abstand oben */
         width: 100%;
         border-collapse: collapse;
        /* Zusammenführen der Tabellenränder */
         border: none;
        /* Äußeren Rahmen entfernen */
    }
    /* Tabellenüberschriften fett und schwarz auf weißem Grund */
     table th {
         font-weight: bold;
         color: #ffffff !important;
         background: red !important; /* seltsamerweise keine Auswirkung */
    }
    
     thead, 
     th {
         background: #ffffff !important;  /* seltsamerweise keine Auswirkung */
    }
    
    
    
     table td {
       font-weight: normal;
       color: #000000 !important;
       background: #ffffff !important;
       border: 1px solid #000000 !important; 
    }
    
    
    /* Vermeidet Seitenumbrüche vor Überschriften, wenn sie am Ende der Seite stehen */
     h1, h2, h3, h4, h5, h6 {
         page-break-before: avoid;
    }
    /* Vermeidet Seitenumbrüche innerhalb von Tabellen */
     table {
         page-break-inside: avoid;
    }
    /* Vermeidet Waisenkinder (einzelne Zeilen am Ende der Seite) */
     figure, h1, h2, h3, h4, h5, h6, p, table {
         orphans: 2;
        /* Mindestanzahl an Zeilen, die auf der Seite bleiben müssen */
         widows: 2;
        /* Mindestanzahl an Zeilen, die auf der nächsten Seite benötigt werden */
         page-break-inside: avoid;
    }
    /* Verhindert, dass eine Überschrift allein auf einer Seite steht */
     h1:only-child, h2:only-child, h3:only-child, h4:only-child, h5:only-child, h6:only-child {
         page-break-after: always;
    }
    /* Verhindert Seitenumbrüche zwischen Überschriften und Tabellen */
     h1 + table, h2 + table, h3 + table, h4 + table, h5 + table, h6 + table {
         page-break-before: avoid;
    }
    /* Setzt Überschriften und Tabellen als inline-block, um sie auf derselben Seite zu halten */
     h1, h2, h3, h4, h5, h6, table {
         display: inline-block;
    }
    /* Verhindert Seitenumbrüche zwischen Überschriften und Texten */
     h1 + *, h2 + *, h3 + *, h4 + *, h5 + *, h6 + * {
         page-break-before: avoid;
    }
    /* Vermeidet einen Umbruch in und nach Listen, die auf eine Überschrift folgen */
    h1 + ul, h2 + ul, h3 + ul, h4 + ul, h5 + ul, h6 + ul,
    h1 + ol, h2 + ol, h3 + ol, h4 + ol, h5 + ol, h6 + ol  {
        page-break-after: avoid;
        page-break-inside: avoid;
    }
    
     /* Verhindert Seitenumbrüche vor sub */
     sub  {
         page-break-before: avoid;
    }
    
    /* Verhindert Seitenumbrüche zwischen Überschriften und Tabellen */
     h1 + table, h2 + table, h3 + table, h4 + table, h5 + table, h6 + table {
         page-break-before: avoid;
    }
    /* Setzt Überschriften und Tabellen als inline-block, um sie auf derselben Seite zu halten */
     h1, h2, h3, h4, h5, h6, table {
         display: inline-block;
    }
    /* Verhindert Seitenumbrüche zwischen Überschriften und Texten */
     h1 + *, h2 + *, h3 + *, h4 + *, h5 + *, h6 + * {
         page-break-before: avoid;
    }
    /* Verhindert Seitenumbrüche zwischen Überschriften und Tabellen */
     h1 + table, h2 + table, h3 + table, h4 + table, h5 + table, h6 + table {
         page-break-before: avoid;
    }
     img + p {
         page-break-after: avoid;
    }
     .inline-title, .inline-title + h1, .inline-title + h2, .inline-title + h3, .inline-title + h4, .inline-title + h5, .inline-title + h6 {
         display: block;
         margin-top: 20mm;
        /* Beispielhafter Abstand von 2 cm zwischen Titel und Überschrift */
    }
     .inline-title::after {
         content: '\A';
         white-space: pre;
    }
    
/* %% Dieser Kommentar über der ersten Überschrift der markdown Datei verhindert lediglich das sich der Titel und die erste Überschrift nebeneinander befinden. %% */
     h1:first-of-type::before {
         /* content: '\A \A';
         content: '\A';   Nur ein und ein Umbruch */
        
         white-space: pre;
         display: block;
         margin-bottom: 10mm;
       
}
 ```
