### ISSUE TITLE
使用Border主题时导出pdf引用文本块样式异常

### ISSUE THREAD

**Issue by qwqw3qee** [l1xnan/obsidian-better-export-pdf#315]
如题，使用border主题时，导出pdf时引用文本块的样式与软件内显示效果不一致
![image](https://github.com/user-attachments/assets/1c0ebf11-f6c0-4a58-8a52-91c34ee7ff3c)

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by qwqw3qee** [comment]
临时解决方案：
```css
.markdown-rendered blockquote {
    position: relative;
    border-radius: var(--radius-s);
    border-inline-start: none;
    padding-inline: calc(16px + var(--blockquote-border-thickness) + var(--blockquote-padding)) var(--blockquote-padding);
    padding-block: var(--blockquote-padding);
}
```
border主题中`border-inline-start: none;`在导出时没有生效，导致引用文本块保留部分obsidian默认样式。可以通过自定义css强制清除这块,css如下。
```css
@media print {
  /* 主 blockquote 样式 */
  .markdown-rendered blockquote {
    border-left: none !important;
  }
}
```
将此css放在`.obsidian\snippets`目录下，在插件中启用css片段选择，并在导出时选中该css即可。
