### ISSUE TITLE
Avoid separating callout when exporting PDF

### ISSUE THREAD

**Issue by xiong-ZH-zq** [l1xnan/obsidian-better-export-pdf#361]
Is there a way to avoid separating callout when exporting PDF? When a callout is separated it looks like the image below. The official export also has this problem. I would love to use this plugin to solve this problem. Thanks for helping in advance.

![图片](https://github.com/user-attachments/assets/829fb414-77d7-423b-848b-c9c1f7b419c7)

**Comment by l1xnan** [comment]
目前没有好的办法，HTML转PDF类的技术方案，没有很好的分页算法，也没有选项来调节分页。你可以通过 HTML 片段手动插入一个分页来临时缓解这个问题
https://developer.mozilla.org/zh-CN/docs/Web/CSS/break-after

**Comment by xiong-ZH-zq** [comment]
找到了个解决方案：使用下面的 CSS 片段可以让它在 callout 前后强制分页：

```css
@media print {
  /* h1:first-of-type {
    page-break-before: avoid;
} */
  h1 {
    page-break-before: always;
  }
  h2,
  h3,
  h4,
  h5,
  h6 {
    page-break-after: avoid;
  }
  .internal-embed {
    page-break-after: avoid;
    page-break-before: avoid;
  }
  .callout {
    page-break-inside: avoid;
  }
}
```

**Comment by qhenry** [comment]
I ran into the same issue with callouts being split across pages during PDF export.

In my case, the callout title stayed at the bottom of one page, while the callout content continued on the next page. Adding print CSS rules for Obsidian callouts fixed the issue locally.

A possible CSS fix:

```css
@media print {
  .print .markdown-preview-view .callout {
    break-inside: avoid;
    break-inside: avoid-page;
    page-break-inside: avoid;
    -webkit-column-break-inside: avoid;
    -webkit-box-decoration-break: clone;
    box-decoration-break: clone;
    orphans: 3;
    widows: 3;
    overflow: visible !important;
  }

  .print .markdown-preview-view .callout-title {
    break-after: avoid;
    break-after: avoid-page;
    page-break-after: avoid;
  }

  .print .markdown-preview-view .callout-content,
  .print .markdown-preview-view .callout-content > :first-child {
    break-before: avoid;
    break-before: avoid-page;
    page-break-before: avoid;
  }
}
```

This does not force very large callouts to fit on one page, but it prevents normal callouts from being separated between the title and the first content block. For oversized callouts, `box-decoration-break: clone` also makes the border/background behave better when the browser has to paginate.

I tested this locally as both a plugin print-style patch and an Obsidian CSS snippet, and it fixed the broken callout pagination in my exported PDF.
