### ISSUE TITLE
功能请求：分页预览功能

### ISSUE THREAD

**Issue by justincnn** [l1xnan/obsidian-better-export-pdf#392]
大神，这个插件太棒了，

请问是否可以增加分页预览的功能，有些md文件需要打印成a4纸，如果有分页预览的功能的话，可以直接调整格式和间距，以实现完美打印

望采纳，谢谢

**Comment by l1xnan** [comment]
这个功能比较难搞，工作量比较大，试了几种简单方案都不理想，后续再看看

**Comment by justincnn** [comment]
> 这个功能比较难搞，工作量比较大，试了几种简单方案都不理想，后续再看看

让用户自己强制插入分页符，这个思路可以实现么？如果类似于word这样的智能分页是很难的

**Comment by xef6273** [comment]
对于PDF进行分页来说，能不能基于标题或者自定义的标记来实施分页呢？比如以一级标题 或者二级标题作为分页参考项，或者插入一些固定的标记来作为检测项，检测到这些内容的时候，从这个地方来实施分页

**Comment by l1xnan** [comment]
> 对于PDF进行分页来说，能不能基于标题或者自定义的标记来实施分页呢？比如以一级标题 或者二级标题作为分页参考项，或者插入一些固定的标记来作为检测项，检测到这些内容的时候，从这个地方来实施分页

```css
.page-end,h2 {
  border-top: 1px solid #ccc;
  padding: 0;
  margin: 0;
}
@media print {
  .page-end,h2 {
    border-top: none !important;
    padding: 0;
    margin: 0;
    break-after: page;
    page-break-after: always;
  }
}
```
正文:
```
<div class="page-end">手动分割</div>

## 自动分割标题
```
