### ISSUE TITLE
Support YAML Front Matter to fill in PDF metadata

### ISSUE THREAD

**Issue by l1xnan** [l1xnan/obsidian-better-export-pdf#85]
Examples:
```yaml
title: My Ttile
author: Alfred E. Newman
subject: Making PDF more usable
keywords: [PDF, searching, metadata, YAML]
date: 2021-03-06
```

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/62e04862-6378-47ec-8018-74a9e72c29fc)
