### ISSUE TITLE
提问：如何修改打印的css

### ISSUE THREAD

**Issue by Kiss-World** [l1xnan/obsidian-better-export-pdf#96]
原因是如果可以从预览看到和打印出一样的效果就好了。目前是字体大小不同。

我感觉pdf的字重了些，希望它打印时更细一些，不知道如何修改

## ob 的大小
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/44720566/4e544a35-d474-4dd2-8a72-c44fead19c75)
## 导出的大小
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/44720566/f1696c90-a07b-4d3d-9709-f57e09dbb656)
## 打印预览的大小
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/44720566/f5889037-25cc-4606-b8c8-742b3e2bb121)

**Comment by l1xnan** [comment]
首先预览是有缩放的，所以大小和实际的没法比较; 如果你想让Obsidian的字体和打印的字体/字号有不一样的设置，可以在`外观`>`CSS代码片段` 中添加自定义的CSS，例如：
```css
@media print {
  body {
    font-size: 20px;
    font-family: "思源宋体" !important;
  }
}
```
从阅读习惯上，网页等显示器阅读我们一般会用无衬线字体（微软雅黑等）看着更清晰，小字号下没有衬线字体的锯齿感（高分屏随意）；PDF需要印刷的一般会选择衬线类字体（思源宋体、霞鹜文楷等），你可以根据自己的喜好进行自定义配置。
